apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web2
  template:
    metadata:
      labels:
        app: my-web2
    spec:
      containers:
      - name: mink
        image: mink:latest
        ports:
        - containerPort: 200